<?php $action = $this->escape($this->element->getAction()); ?>
<?php $method = $this->escape($this->element->getMethod()); ?>


<form action="<?php echo $action; ?>" method="<?php echo $method; ?>">
    <fieldset class="join-form">
        <div class="title">
            Join Now

            <?php foreach ($this->element->getErrorMessages() as $message) : ?>
                <div class="required"><?php echo $this->escape($message); ?></div>
            <?php endforeach; ?>
        </div>

        <fieldset class="field-group">
            <?php echo $this->element->first_name; ?>
            <?php echo $this->element->last_name; ?>
            <?php echo $this->element->email; ?>
            <?php echo $this->element->password; ?>
            <?php echo $this->element->confirmation; ?>
            <?php echo $this->element->submit; ?>
        </fieldset>
    </fieldset>
</form>
