<div class="footer_inner">
    <ul>
        <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index')); ?>">Home</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'about-us', 'action' => 'index')); ?>">About Us</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'terms-conditions', 'action' => 'index')); ?>">Terms & Conditions</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'privacy-policy', 'action' => 'index')); ?>">Privacy Policy</a></li>
    </ul>
    
    <div class="clear"></div>
    
    <div class="decor-line"></div>
</div>
